version: '3'
services:
  backend:
    build:
      context: ./Backend 
    ports:
      - "8000:8000"  
    environment:
      - ENVIRONMENT=production 

  frontend:
    build:
      context: ./Frontend/web-learning-neuronet 
    ports:
      - "80:80"  
    environment:
      - REACT_APP_BACKEND="http://localhost:8000"  
